src/src/Tdom/UserBundle/Entity/User.php
<?php

namespace Tdom\UserBundle\Entity;

use FOS\UserBundle\Entity\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Intl\Intl;
use Tdom\UserBundle\Validator\InvalidAge;

/**
 * User
 *
 * @ORM\Table()
 * @ORM\HasLifecycleCallbacks
 * @ORM\Entity(repositoryClass="Tdom\UserBundle\Entity\UserRepository")
 * @InvalidAge
 */
class User extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     * @Assert\NotBlank()
     * @ORM\Column(name="nick_name", type="string", length=255)
     */
    private $nickName;

    /**
     * @var string
     * @Assert\NotBlank()
     * @ORM\Column(name="full_name", type="string", length=255)
     */
    private $fullName;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birth_day", type="date", length=255)
     */
    private $birthDay;

    /**
     * @var string
     *
     * @ORM\Column(name="country", type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", length=255, nullable=true)
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @var string
     * @ORM\Column(name="location", type="string", length=255, nullable=true)
     */
    private $location;

    /**
     * @var User
     *
     * @ORM\ManyToMany(targetEntity="Tdom\AdminBundle\Entity\Game", inversedBy="users")
     */
    private $games;

    /**
     * @Assert\File(maxSize="6000000")
     */
    private $file;

    private $temp;

    private $totalUnreadMessage;

    /**
     * @ORM\OneToMany(targetEntity="Tdom\MessageBundle\Entity\UserMessage", mappedBy="sourceUser")
     */
    private $userMessages;


    public function __construct() {
        parent::__construct();
        $this->games = new ArrayCollection();
        $this->username = uniqid();
        $this->birthDay = new \DateTime();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() {
        return $this->id;
    }

    /**
     * @param  $avatar
     * @return $this
     */
    public function setAvatar($avatar) {
        $this->avatar = $avatar;
        return $this;
    }

    /**
     * @return string
     */
    public function getAvatar() {
        return $this->avatar;
    }

    /**
     * @param \DateTime $birthDay
     * @return $this
     */
    public function setBirthDay($birthDay) {
        $this->birthDay = $birthDay;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getBirthDay() {
        return $this->birthDay;
    }

    /**
     * @param string $city
     * @return $this
     */
    public function setCity($city) {
        $this->city = $city;

        return $this;
    }

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param $country
     * @return $this
     */
    public function setCountry($country) {
        $this->country = $country;

        return $this;
    }

    /**
     * @return string
     */
    public function getCountry() {
        return $this->country;
    }

    /**
     * @param string $description
     * @return $this
     */
    public function setDescription($description) {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription() {
        return $this->description;
    }

    /**
     * @param string $fullName
     * @return $this
     */
    public function setFullName($fullName) {
        $this->fullName = $fullName;

        return $this;
    }

    /**
     * @return string
     */
    public function getFullName() {
        return $this->fullName;
    }

    /**
     *
     * @param string $nickName
     * @return $this
     */
    public function setNickName($nickName) {
        $this->nickName = $nickName;

        return $this;
    }

    /**
     * @return string
     */
    public function getNickName() {
        return $this->nickName;
    }

    /**
     * @param \Tdom\AdminBundle\Entity\Game $game
     */
    public function addGames($game) {
        $this->games[] = $game;
    }

    /**
     * Remove game
     *
     * @param \Tdom\AdminBundle\Entity\Game $game
     */
    public function removeGame($game) {
        $this->games->removeElement($game);
    }

    /**
     * @return \Tdom\UserBundle\Entity\User
     */
    public function getGames() {
        return $this->games;
    }

    /**
     * @param string $location
     * @return $this
     */
    public function setLocation($location) {
        $this->location = $location;

        return $this;
    }

    /**
     * @return string
     */
    public function getLocation() {
        return $this->location;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null) {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->avatar)) {
            // store the old name to delete after the update
            $this->temp = $this->avatar;
            $this->avatar = null;
        } else {
            $this->avatar = 'initial';
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->avatar = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->avatar);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        $this->file = null;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {
        if ($file = $this->getAbsolutePath()) {
            unlink($file);
        }
    }

    public function getAbsolutePath() {
        return null === $this->avatar
            ? null
            : $this->getUploadRootDir().'/'.$this->avatar;
    }

    public function getWebPath() {
        return null === $this->avatar
            ? null
            : $this->getUploadDir().'/'.$this->avatar;
    }

    protected function getUploadRootDir() {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir() {

        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads';
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    public function unsetPassword(){
        unset($this->password);
        $this->plainPassword = null;
    }

    public function getAge() {
        $now      = new \DateTime();
        $birthday = $this->getBirthDay();
        $interval = $now->diff($birthday);
        return $interval->format('%y');
    }

    public function getCountryFullName() {
        return Intl::getRegionBundle()->getCountryName($this->getCountry());
    }

    /**
     * @param mixed $userMessages
     */
    public function addUserMessages($userMessages) {
        $this->userMessages[] = $userMessages;
    }

    /**
     * @return mixed
     */
    public function getUserMessages() {
        return $this->userMessages;
    }

    public function __toString() {
        return $this->getNickName();
    }

    /**
     * @param mixed $totalUnreadMessage
     */
    public function setTotalUnreadMessage($totalUnreadMessage) {
        $this->totalUnreadMessage = $totalUnreadMessage;
    }

    /**
     * @return mixed
     */
    public function getTotalUnreadMessage() {
        return $this->totalUnreadMessage;
    }
}

src/src/Tdom/UserBundle/Controller/UserController.php
<?php

namespace Tdom\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\DependencyInjection\ContainerAware;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use FOS\UserBundle\Model\UserInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Tdom\GameBundle\Model\FindGamer as FindUser;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;


class UserController extends Controller
{

    /**
     * @Route("/profile/change/password", name="userChangePassword")
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @throws AccessDeniedException
     */
    public function changePasswordAction()
    {
        $user = $this->container->get('security.context')->getToken()->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }

        $form = $this->container->get('fos_user.change_password.form');
        $formHandler = $this->container->get('fos_user.change_password.form.handler');

        $process = $formHandler->process($user);
        if ($process) {
            $this->setFlash('fos_user_success', 'change_password.flash.success');
            $rendered = $this->renderView("TdomUserBundle:ChangePassword:email.txt.twig", array('user' => $user));
            $this->sendEmail($rendered,$user);
            return new RedirectResponse($this->getRedirectionUrl($user));
        }

        return $this->container->get('templating')->renderResponse(
            'FOSUserBundle:ChangePassword:changePassword.html.'.$this->container->getParameter('fos_user.template.engine'),
            array('form' => $form->createView())
        );
    }

    /**
     * Generate the redirection url when the resetting is completed.
     *
     * @param \FOS\UserBundle\Model\UserInterface $user
     *
     * @return string
     */
    protected function getRedirectionUrl(UserInterface $user)
    {
        return $this->container->get('router')->generate('fos_user_profile_edit');
    }

    /**
     * @param string $action
     * @param string $value
     */
    protected function setFlash($action, $value)
    {
        $this->container->get('session')->getFlashBag()->set($action, $value);
    }

    private function sendEmail($renderedTemplate, $user) {

        $renderedLines = explode("\n", trim($renderedTemplate));
        $subject = $renderedLines[0];
        $body = implode("\n", array_slice($renderedLines, 1));

        $message = \Swift_Message::newInstance()
        ->setSubject($subject)
        ->setFrom(array('noreply@tabledom.com' => "Tabledom"))
        ->setTo($user->getEmail())
        ->setBody($body);

        $message->setContentType("text/html");

        $this->get('mailer')->send($message);
    }

    /**
     * User Add contact action
     *
     * @Route("/profile/add/connect/{userId}/{ajax}", name="userAddContact")
     * @param $userId
     * @param $ajax
     * @throws Exception
     * @return JsonResponse
     */
    public function addContactAction($userId, $ajax = false) {
        $response = new JsonResponse();

        /* @var \Tdom\UserBundle\Manager\UserManager $um */
        $um = $this->get("tdom.user.manager");

        /* @var \Tdom\UserBundle\Entity\User $targetUser */
        $targetUser = $this->getDoctrine()->getRepository('TdomUserBundle:User')->find($userId);

        if(!$targetUser)
            throw new Exception("User not found!!");


        $userConnect = $um->addToContact($targetUser);

        if($ajax) {
            if($userConnect) {

                $responseArr = array ("button" => "Remove from my contacts", "url" => $this->generateUrl(
                        'userRemoveContact', array('userId' => $targetUser->getId())));
                $responseArr['user'] = $this->renderView('TdomUserBundle:User:Partials/user.html.twig', array('user' => $targetUser));
                $response->setData($responseArr);
                return $response;
            }
        }

        return $this->redirect($this->generateUrl('socialiseAction'), 301);
    }

    /**
     * Remove Contact Action
     *
     * @Route("/profile/remove/connect/{userId}/{ajax}", name="userRemoveContact")
     * @param $userId
     * @param $ajax
     * @throws Exception
     * @return JsonRespone
     */
    public function removeContactAction($userId, $ajax = false) {
        $response = new JsonResponse();
        /* @var \Tdom\UserBundle\Entity\User $targetUser */
        $targetUser = $this->getDoctrine()->getRepository('TdomUserBundle:User')->find($userId);

        if(!$targetUser)
            throw new Exception("User not found!!");

        /** @var \Tdom\UserBundle\Entity\UserConnectRepository $userConnectRepo */
        $userConnectRepo = $this->getDoctrine()->getRepository("TdomUserBundle:UserConnect");

        $userConnect = $userConnectRepo->checkExistingUserConnect($targetUser->getId(), $this->getUser()->getId());

        if($userConnect) {
            $this->getDoctrine()->getManager()->remove($userConnect);
            $this->getDoctrine()->getManager()->flush();

            if($ajax) {
                $responseArr = array ("button" => "Add to my contacts", "url" => $this->generateUrl(
                        'userAddContact', array('userId' => $targetUser->getId())));

                $response->setData($responseArr);

            }
            else {
                $this->redirect($this->generateUrl('gamerFind'));
            }
        }

        return $response;
    }

    /**
     * User public profile page
     *
     * @Route("/user/{userId}", name="userProfile")
     * @param $userId
     * @return JsonResponse
     * @throws NotFoundHttpException
     */
    public function userProfileAction($userId) {
        /* @var \Tdom\GameBundle\Manager\GameManager $gm */
        $gm = $this->get("tdom.game.manager");

        /* @var \Tdom\UserBundle\Entity\User $user */
        $user = $this->getDoctrine()->getRepository('TdomUserBundle:User')->find($userId);

        if(!$user)
            throw new NotFoundHttpException("User not found!!");

        /** @var \Tdom\UserBundle\Entity\UserConnectRepository $userConnectRepo */
        $userConnectRepo = $this->getDoctrine()->getRepository("TdomUserBundle:UserConnect");

        if ($this->getUser())
            $userConnect = $userConnectRepo->checkExistingUserConnect($user->getId(), $this->getUser()->getId());

        $categoriesAndGames = $gm->findUserGames($user);
        if ($this->getRequest()->get('json')) {
            $response = new JsonResponse();

            $this->data['success'] = true;
            $this->data['content'] = $this->renderView('TdomUserBundle:User:userProfile.html.twig',
                array(
                    'categories' => $categoriesAndGames,
                    'isPublic' => true,
                    'json' => true,
                    'userConnect' => (isset($userConnect))? $userConnect : "",
                    'user' => $user
                ));
            $this->data['nickname'] = $user->getNickName();
            $response->setData($this->data);
            return $response;
        }

        return $this->render('TdomUserBundle:User:userProfile.html.twig',
            array(
                'categories' => $categoriesAndGames,
                'isPublic' => true,
                'userConnect' => (isset($userConnect))? $userConnect : "",
                'user' => $user
            ));
    }

    /**
     * Find user contacts
     *
     * @Route("/profile/find/connect/{q}", name="findUserContacts")
     * @param string $q
     * @return JsonResponse
     */
    public function findUsersAction($q = "") {
        $response = new JsonResponse();
        $responseArr = array();
        /** @var \Tdom\UserBundle\Manager\UserManager $um */
        $um = $this->get('tdom.user.manager');
        $connectUsers = $um->findUsers($q);
        $responseArr['data'] = $this->renderView('TdomUserBundle:User:Partials/list.html.twig' , array('connectUsers' => $connectUsers, 'ajax' => true));
        $response->setData($responseArr);
        return $response;
    }
}

src/src/Tdom/UserBundle/Resources/views/User/profile.html.twig
{% extends "TdomViewBundle::layout.html.twig" %}
{% block title %}TdomViewBundle:Home:index{% endblock %}
{% block active %} active {% endblock active %}
{% block content %}
    <div class="content_bg">
        <div>
            <div class="col-lg-8 col-lg-offset-2">
                <div class="col-lg-6 col-lg-offset-3">
                    <div style="padding: 10% 0%">
                        <form class="form-horizontal">
                            <div class="logo" style="padding-bottom: 10px">
                                <img class="img-responsive" src="{{ asset('bundles/tdomview/images/Tabledom_logo.png') }}" />
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="col-lg-4 control-label">Email Address</label>
                                <div class="col-lg-7">
                                    <input class="form-control" id="inputEmail" placeholder="email" type="email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="password" class="col-lg-4 control-label">Password</label>
                                <div class="col-lg-7">
                                    <input class="form-control" id="password" placeholder="password" type="password">
                                    <a href="">Forgot password?</a>
                                </div>
                            </div>
                            <div class="form-group">
                                <label  class="col-lg-4 control-label"></label>
                                <div class="col-lg-7">
                                    <input type="submit" class="btn btn-danger btn-sm" style="width:100%" value="Login" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label  class="col-lg-4 control-label"></label>
                                <div class="col-lg-7">
                                    <a href="">Registration &gt</a> <br />
                                    <a href="">Continue without registration &gt</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/src/Tdom/UserBundle/Resources/views/User/registration.html.twig
{% block content %}
    <div class="content_bg">
        <div class="col-lg-8 col-lg-offset-2">
             <div class="content-details">
                 <h3 class="content-details-title"> {{ "Registration" | trans }} </h3>
                 {% include 'TdomUserBundle:User:Partials/register_form.html.twig' %}
             </div>
        </div>
    </div>
{% endblock content %}

src/src/Tdom/UserBundle/Resources/views/User/userProfile.html.twig
{% extends json is not defined ? "TdomViewBundle::layout.html.twig" : 'TdomViewBundle::ajax.html.twig' %}
{% block title %}{{ user.nickName }}{% endblock %}
{% block content %}
{% if json is not defined %}
    <div class="content_bg">
    <div class="col-lg-8 col-lg-offset-2">
{% endif %}
    <div class="content-details">
        <div class="row-fluid user-info-details form-horizontal" style="overflow: hidden">
            <div class="col-sm-8 nopadding">
                <div class="list-group">
                    <label class="col-sm-2 nopadding">{{ "Real name" | trans }}</label>
                    <div class="col-sm-10">
                        {{ user.fullName }}
                    </div>
                </div>

                <div class="list-group">
                    <label class="col-sm-2 nopadding">{{ "E-mail" | trans }}</label>
                    <div class="col-sm-10">
                       {% if app.user %}
                           {{ user.email }}
                       {% else %}
                           <a href="{{ path('fos_user_security_login') }}">Email address is available for registered users</a>
                        {% endif %}
                    </div>
                </div>

                <div class="list-group">
                    <label class="col-sm-2 nopadding">{{ "Age" | trans }}</label>
                    <div class="col-sm-10">
                       {{ user.age }} {{ "years" | trans }}
                    </div>
                </div>
                <div class="list-group">
                    <label class="col-sm-2 nopadding">{{ "Location" | trans }}</label>
                    <div class="col-sm-10">
                        {{ user.city }}, {{ user.countryFullName }}
                    </div>
                </div>
                <div class="list-group">
                    <label class="col-sm-2 nopadding">{{ "Description" | trans }}</label>
                    <div class="col-sm-10">
                        {{ user.description }}
                    </div>
                </div>
            </div>
            <div class="col-sm-4 nopadding">
                <div class="profile-picture nopadding">
                    {% if user.avatar %}
                        {%  set img =  asset('uploads/'~user.avatar) %}
                        <img src="{{ web_image(img).resize(300) }}" class="img-responsive" />
                    {% else %}
                        <img  class="img-responsive drop-area" style="width:200px; height: 200px" src="{{ asset('bundles/tdomuser/images/default_avatar.jpeg') }}" />
                    {% endif %}
                </div>
            </div>
            <div class="list-group" style="">
                <div class="col-lg-10 nopadding">
                    {% if json is defined %}
                        <a href="#" class="btn btn-danger" id="showonmap"> {{ "Show on map" |trans }} </a>
                    {% endif %}
                    {% if userConnect %}
                        <a href="{{ path('userRemoveContact', {'userId' : user.id}) }}" class="btn btn-danger"  id="addcontacts" >{{ "Remove from my contacts" | trans }} </a>
                    {% else %}
                        <a href="{{ path('userAddContact', {'userId' : user.id}) }}"  class="btn btn-danger" data-login="{% if app.user %}{{ app.user.id }}{% endif %}"  id="addcontacts" >{{ "Add to my contacts" | trans }} </a>
                    {% endif %}
                    <a href="{{ path('socialiseAction', {'userId' : user.id }) }}" class="btn btn-danger" data-login="{% if app.user %}{{ app.user.id }}{% endif %}" id="send_message" > {{ "Send message" | trans }} </a>
                </div>
            </div>
        </div>
        <div class="user-games">
            {% include 'TdomGameBundle:Game:Partials/games.html.twig' %}
        </div>
    </div>
 {% if json is not defined %}
     </div>
     </div>
{%  endif %}
    <div class="modal fade" id="confirm-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    {{ "Confirmation" | trans }}
                </div>
                <div class="modal-body">
                    {{ 'Please login or register.' | trans }}
                </div>
                <div class="modal-footer">
                    <a href="{{ path('fos_user_security_login') }}" class="btn btn-danger danger">{{ "Login" | trans}}</a>
                    <a href="{{ path('fos_user_registration_register') }}" class="btn btn-danger danger">{{ "Register" | trans}}</a>
                    <button type="button" onclick="jQuery('#confirm-modal').modal('hide')" class="btn btn-default" >{{ "Cancel" | trans }}</button>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}